
# Nginx будет просто проксировать все запросы к booktracker. Никакой статики, только reverse proxy.

events {
    worker_connections 1024;
}

http {
    server {
        # nginx слушает снаружи на 80
        listen 80;

        location / {
            # все запросы проксируем к booktracker
            # booktracker — это имя сервиса в Compose, работает как hostname
            proxy_pass http://booktracker:8080;

            # передаём оригинальные заголовки чтобы приложение
            # видело реальный IP клиента, а не IP nginx
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}